CSUN-SeniorDesign/matabit-blog

- content/posts/shahed-week-1.md
Explanation of how/why we created the VPC/Routing Tables/IGW.
> added blog post about vpc

- content/posts/anthony-week-1.md
Blog post about setting up Hugo and buying a domain name.
> Anthony's week1 blog post

- content/posts/mario-week-1.md
> Mario blog post week1

- content/posts/thomas-week-1.md
add updated thomas blog to thomas-week-1 branch
> Thomas blog post week 1

- content/posts/shahed-week-2.md
Added blog post for week 2 and wrote about how we installed the SSL certificates.
Referencing Issue #23
> added blog post about ssl certificates

- .gitignore
- config.toml
- content/about.md
- deploy.sh
Created a small bash script to automatically deploy blog. Also changed the url in the config.toml to properly map using subdomains.
> Added deploy script

- content/posts/mario-week-2.md
> Mario-week2-post

- content/posts/thomas-week-2.md
> thomas week 2 blog post

- content/posts/shahed-week-3.md
Write up about week 3. wrote about iam, ec2 and nat
> blog post week 3 write up

- content/posts/thomas-week-3.md
adding thomas week 3 blog post
> thomas week 3 blog post

- content/posts/anthony-week-3.md
> Week 3 post about Terraform-VPC

- content/posts/mario-week-3.md
> Mario-week-3

- content/posts/shahed-week-4.md
added week 4 blog post. please review if enough content has been added
> shahed-blog-post-week-4 has been added

- content/posts/mario-week-4.md
> mario-week-4-blog

- content/posts/thomas-week-4.md
adding thomas' week 4 blog post
> thomas week 4 blog post

- content/posts/mario-week-5.md
> mario-blog-week-5

- content/posts/shahed-week-5.md
Completed Blog Post for week 5
> Blog Post Week 5 Shahed posted

- content/posts/thomas-week-5.md
> thomas week 5 blog

- content/posts/shahed-week-6.md
Please review and merge blog post 6
> completed blog post 6

- content/posts/mario-week-6.md
> Mario-week-6-blog

- content/posts/thomas-week-6.md
> thomas week 6 blog post

- content/posts.mario-week-7.md
> mario-week7-blog

- content/posts/thomas-week-7.md
adding thomas blog post week 7
> thomas week 7 blog post

- .circleci/config.yml
- Dockerfile
- README.md
- nginx.template
Added Dockerfile, and CircleCI config to create Docker Image on successful test and then push to AWS ECR for ECS.
> Docker circleci

- content/posts/shahed-week-8.md
> Shahed week 8

- content/posts/anthony-week-8.md
Dont deploy into production on CircleCI yet. Save it for the demo
> Anthony week 8

- content/posts/thomas-week-8.md
> Thomas week 8 blog

- content/posts/shahed-week-9.md
> finished Blog 9

- content/posts/mario-week-9.md
> week 9 blog

- content/posts/mario-week-10.md
> week-10-blog
